// Registro de bancos, gateways e instituições — usado nos ícones das contas.
// `logo` aponta para assets/bancos/<arquivo>. Sem logo, o app cai no monograma com a cor.
export const BANCOS = [
  { id:'inter',        nome:'Banco Inter',        cor:'#FF7A00', compe:'077', logo:'inter.png' },
  { id:'btg',          nome:'BTG Pactual',        cor:'#0A1E5B', compe:'208', logo:'btg.png' },
  { id:'stone',        nome:'Stone',              cor:'#00A868', compe:'197', logo:'stone.svg' },
  { id:'pagarme',      nome:'Pagar.me',           cor:'#00AF55', compe:'',    logo:'pagarme.svg', tipo:'gateway' },
  { id:'itau',         nome:'Itaú',               cor:'#EC7000', compe:'341', logo:'itau.png' },
  { id:'bradesco',     nome:'Bradesco',           cor:'#CC092F', compe:'237', logo:'bradesco.png' },
  { id:'santander',    nome:'Santander',          cor:'#EC0000', compe:'033', logo:'santander.png' },
  { id:'bb',           nome:'Banco do Brasil',    cor:'#1F3A93', compe:'001', logo:'bb.png' },
  { id:'caixa',        nome:'Caixa Econômica',    cor:'#005CA9', compe:'104', logo:'caixa.svg' },
  { id:'nubank',       nome:'Nubank',             cor:'#820AD1', compe:'260', logo:'nubank.png' },
  { id:'c6',           nome:'C6 Bank',            cor:'#1A1A1A', compe:'336', logo:'c6.png' },
  { id:'sicoob',       nome:'Sicoob',             cor:'#00594F', compe:'756', logo:'sicoob.png' },
  { id:'sicredi',      nome:'Sicredi',            cor:'#3FA435', compe:'748', logo:'sicredi.svg' },
  { id:'safra',        nome:'Safra',              cor:'#0B2A57', compe:'422', logo:'safra.png' },
  { id:'xp',           nome:'XP',                 cor:'#111111', compe:'102', logo:'xp.png' },
  { id:'bs2',          nome:'BS2',                cor:'#1B3FA0', compe:'218', logo:'bs2.png' },
  { id:'original',     nome:'Banco Original',     cor:'#1DB954', compe:'212', logo:'original.png' },
  { id:'neon',         nome:'Neon',               cor:'#00A5F0', compe:'735', logo:'neon.png' },
  { id:'cora',         nome:'Cora',               cor:'#FE3E6D', compe:'403', logo:'cora.png' },
  { id:'unicred',      nome:'Unicred',            cor:'#0E7C6B', compe:'136', logo:'unicred.png' },
  { id:'ailos',        nome:'Ailos',              cor:'#1E6FB3', compe:'085', logo:'ailos.png' },
  { id:'modal',        nome:'Modal',              cor:'#1AA3A6', compe:'746', logo:'modal.png' },
  { id:'pan',          nome:'Banco Pan',          cor:'#00A8E1', compe:'623', logo:'pan.png' },
  { id:'bv',           nome:'Banco BV',           cor:'#1F3F99', compe:'655', logo:'bv.png' },
  { id:'clara',        nome:'Clara',              cor:'#1B1B1F', compe:'',    logo:'clara.png', tipo:'cartao' },
  { id:'contasimples', nome:'Conta Simples',      cor:'#111111', compe:'',    logo:'contasimples.png' },
  { id:'infinitepay',  nome:'InfinitePay',        cor:'#1C1C1C', compe:'',    logo:'infinitepay.png', tipo:'gateway' },
  { id:'mercadopago',  nome:'Mercado Pago',       cor:'#009EE3', compe:'323', logo:'mercadopago.png', tipo:'gateway' },
  { id:'pagbank',      nome:'PagBank',            cor:'#FFC801', compe:'290', logo:'pagbank.png', tipo:'gateway' },
  { id:'picpay',       nome:'PicPay',             cor:'#21C25E', compe:'380', logo:'picpay.png' },
  { id:'stripe',       nome:'Stripe',             cor:'#635BFF', compe:'',    logo:'stripe.png', tipo:'gateway' },
  { id:'paypal',       nome:'PayPal',             cor:'#003087', compe:'',    logo:'paypal.png', tipo:'gateway' },
  { id:'shopify',      nome:'Shopify Payments',   cor:'#5E8E3E', compe:'',    logo:'shopify.png', tipo:'gateway' },
  { id:'appmax',       nome:'Appmax',             cor:'#7B5CF6', compe:'',    logo:'appmax.png', tipo:'gateway' },
  { id:'cartpanda',    nome:'Cartpanda',          cor:'#2C6BED', compe:'',    logo:'cartpanda.png', tipo:'gateway' },
  { id:'hotmart',      nome:'Hotmart',            cor:'#F04E23', compe:'',    logo:'hotmart.png', tipo:'gateway' },
  { id:'mercadolivre', nome:'Mercado Livre',      cor:'#FFE600', compe:'',    logo:'mercadolivre.png', tipo:'gateway' },
  { id:'amazon',       nome:'Amazon',             cor:'#FF9900', compe:'',    logo:'amazon.png', tipo:'gateway' },
  { id:'asaas',        nome:'Asaas',              cor:'#0030B9', compe:'461', logo:'asaas.png', tipo:'gateway' },
  { id:'efi',          nome:'Efí (Gerencianet)',  cor:'#F37021', compe:'364', logo:'efi.png', tipo:'gateway' },
  { id:'getnet',       nome:'Getnet',             cor:'#E30613', compe:'',    logo:'getnet.png', tipo:'gateway' },
  { id:'sumup',        nome:'SumUp',              cor:'#111111', compe:'',    logo:'sumup.png', tipo:'gateway' },
  { id:'wise',         nome:'Wise',               cor:'#9FE870', compe:'',    logo:'wise.png' },
  { id:'nomad',        nome:'Nomad',              cor:'#F5C400', compe:'',    logo:'nomad.png' },
  { id:'husky',        nome:'Husky',              cor:'#E4007C', compe:'',    logo:'husky.png' },
  { id:'remessa',      nome:'Remessa Online',     cor:'#2D5BFF', compe:'',    logo:'remessa.png' },
  { id:'caixinha',     nome:'Caixa (dinheiro)',   cor:'#0A1B3D', compe:'',    logo:'caixinha.svg', tipo:'caixa' },
  { id:'cartao',       nome:'Cartão de crédito',  cor:'#2F6BE0', compe:'',    logo:'cartao.svg', tipo:'cartao' },
  { id:'outro',        nome:'Outro',              cor:'#5B667E', compe:'',    logo:null },
];

export const BANCO_MAP = Object.fromEntries(BANCOS.map(b => [b.id, b]));
export function banco(id){ return BANCO_MAP[id] || BANCO_MAP.outro; }
export function logoUrl(id){ const b = banco(id); return b.logo ? `assets/bancos/${b.logo}` : null; }

export const TIPOS_CONTA = [
  { id:'corrente',      nome:'Conta corrente',  icone:'ti-building-bank' },
  { id:'poupanca',      nome:'Poupança',        icone:'ti-pig-money' },
  { id:'investimento',  nome:'Investimento',    icone:'ti-chart-line' },
  { id:'gateway',       nome:'Gateway / Adquirente', icone:'ti-credit-card-pay' },
  { id:'cartao',        nome:'Cartão de crédito', icone:'ti-credit-card' },
  { id:'caixa',         nome:'Caixa (dinheiro)', icone:'ti-cash' },
];
